title: Emilio Ure√±a ‚Äî Senior DevOps Engineer # name of the site
author: Emilio Ure√±a # name of site's author
email: contact@e1000.es # email of site's author
url: https://www.e1000.es # root address of the site
baseurl: "" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  I'm Emilio Ure√±a, a Senior DevOps and Platform Engineer. I build reliable, scalable cloud and Kubernetes platforms
  and help teams ship faster with strong automation and observability.
location: Spain
github_username: eltioemil
linkedin_username: emiliourena


permalink: /:slug.html

favicon: "logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

# remote_theme: riggraz/no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please

theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: '<span class="emoji-large">üè†</span> Back' # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page
  lowercase_titles: true # show titles in lowercase in lists

sass:
  style: expanded

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  # - jektex

# jektex:
#   cache_dir: ".jektex-cache"
#   ignore: ["*.xml"]
#   silent: true
#   macros:
#     - ["\\Q", "\\mathbb{Q}"]
#     - ["\\C", "\\mathbb{C}"]
